Nous allons, dans ce fichier, mettre en place l'algo de PPO pour notre agent RL.

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
!pip install gymnasium

Requirement already satisfied: gymnasium in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (2.2.6)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (3.1.2)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (0.0.4)

In [5]:
!pip install gym_trading_env

Requirement already satisfied: gym_trading_env in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (0.3.5)
Requirement already satisfied: pandas>=1.5.3 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.3.3)
Requirement already satisfied: numpy>=1.21.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.2.6)
Requirement already satisfied: gymnasium>=0.28.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (1.2.2)
Requirement already satisfied: flask==2.2.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.2.5)
Requirement already satisfied: pyecharts>=2.0.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.0.9)
Requirement already satisfied: ccxt==3.0.59 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (3.0.59)
Requirement already satisfied: nest_asyncio in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (1.6.0)
Requirement already satisfied: setuptools>=60.9.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (80.9.0)
Requirement already satisfied: certifi>=2018.1.18 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (2025.11.12)
Requirement already satisfied: requests>=2.18.4 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (2.32.5)
Requirement already satisfied: cryptography>=2.6.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (46.0.3)
Requirement already satisfied: aiohttp>=3.8 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (3.13.2)
Requirement already satisfied: aiodns>=1.1.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (3.6.1)
Requirement already satisfied: yarl>=1.7.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (1.22.0)
Requirement already satisfied: Werkzeug>=2.2.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (3.1.4)
Requirement already satisfied: Jinja2>=3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (3.1.6)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (2.2.0)
Requirement already satisfied: click>=8.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (8.3.1)
Requirement already satisfied: pycares<5,>=4.9.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiodns>=1.1.1->ccxt==3.0.59->gym_trading_env) (4.11.0)
Requirement already satisfied: cffi>=1.5.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym_trading_env) (2.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (0.4.1)
Requirement already satisfied: idna>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from yarl>=1.7.2->ccxt==3.0.59->gym_trading_env) (3.11)
Requirement already satisfied: typing-extensions>=4.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiosignal>=1.4.0->aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (4.15.0)
Requirement already satisfied: pycparser in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from cffi>=1.5.0->pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym_trading_env) (2.23)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from click>=8.0->flask==2.2.5->gym_trading_env) (0.4.6)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium>=0.28.1->gym_trading_env) (3.1.2)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium>=0.28.1->gym_trading_env) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from Jinja2>=3.0->flask==2.2.5->gym_trading_env) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym_trading_env) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym_trading_env) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym_trading_env) (2025.3)
Requirement already satisfied: prettytable in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pyecharts>=2.0.2->gym_trading_env) (3.17.0)
Requirement already satisfied: simplejson in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pyecharts>=2.0.2->gym_trading_env) (3.20.2)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->gym_trading_env) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests>=2.18.4->ccxt==3.0.59->gym_trading_env) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests>=2.18.4->ccxt==3.0.59->gym_trading_env) (2.6.2)
Requirement already satisfied: wcwidth in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from prettytable->pyecharts>=2.0.2->gym_trading_env) (0.2.14)

In [4]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (2.2.6)

In [3]:
import numpy as np
import pandas as pd
import gymnasium as gym
import gym_trading_env

In [4]:
def preprocess(df):
    df = df.sort_index()
    df = df.dropna()
    df = df.drop_duplicates()

    df['feature_close'] = (df['close'] - df['close'].mean()) / df['close'].std()

    return df

df = preprocess(pd.read_pickle('./data/yfinance-AAPL-1h.pkl'))
df.head(20)

,open,high,low,close,volume,date_close,feature_close
date_open,,,,,,,
2023-11-21 14:30:00,191.410004,191.520004,190.270004,190.347504,8992766,2023-11-21 15:30:00,-0.953609
2023-11-21 15:30:00,190.350006,190.470001,189.740005,189.942001,5681421,2023-11-21 16:30:00,-0.969213
2023-11-21 16:30:00,189.940002,190.320007,189.830002,190.274994,3359800,2023-11-21 17:30:00,-0.956399
2023-11-21 17:30:00,190.276993,190.600006,190.039993,190.119995,3112369,2023-11-21 18:30:00,-0.962363
2023-11-21 18:30:00,190.119995,190.615005,190.085007,190.380005,2874142,2023-11-21 19:30:00,-0.952358
2023-11-21 19:30:00,190.382797,190.710007,190.289993,190.649994,3442863,2023-11-21 20:30:00,-0.941969
2023-11-21 20:30:00,190.645004,190.729996,190.289993,190.660004,5535871,2023-11-21 21:30:00,-0.941583
2023-11-22 14:30:00,192.360001,192.929993,191.429993,191.931503,11546645,2023-11-22 15:30:00,-0.892655
2023-11-22 15:30:00,191.949997,192.369995,191.389999,191.660004,4786188,2023-11-22 16:30:00,-0.903103
2023-11-22 16:30:00,191.660004,191.960007,191.479996,191.914993,3340080,2023-11-22 17:30:00,-0.893291
2023-11-22 17:30:00,191.914993,192.089996,191.639999,192.005005,3467320,2023-11-22 18:30:00,-0.889827
2023-11-22 18:30:00,192.009995,192.030304,191.490005,191.634995,3409564,2023-11-22 19:30:00,-0.904065
2023-11-22 19:30:00,191.639999,191.639999,190.824997,191.512497,3992146,2023-11-22 20:30:00,-0.908779
2023-11-22 20:30:00,191.520004,191.699997,191.220001,191.300003,3537662,2023-11-22 21:30:00,-0.916956
2023-11-24 14:30:00,190.869995,190.899994,189.300003,189.460007,7873135,2023-11-24 15:30:00,-0.987760
2023-11-24 15:30:00,189.470001,189.669998,189.250000,189.610001,4853829,2023-11-24 16:30:00,-0.981988
2023-11-24 16:30:00,189.600006,189.788895,189.350006,189.539993,3827135,2023-11-24 17:30:00,-0.984682
2023-11-27 14:30:00,190.250702,190.299896,188.899994,189.059998,8344466,2023-11-27 15:30:00,-1.003153
2023-11-27 15:30:00,189.070007,189.500000,189.009995,189.494995,3959357,2023-11-27 16:30:00,-0.986414
2023-11-27 16:30:00,189.490005,190.509995,189.440002,190.369995,4866435,2023-11-27 17:30:00,-0.952743

In [ ]:
env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

In [11]:
pip install stable-baselines3[extra]

Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Collecting stable-baselines3[extra]
  Downloading stable_baselines3-2.7.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (1.2.2)
Requirement already satisfied: numpy<3.0,>=1.20 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (2.2.6)
Collecting torch<3.0,>=2.3 (from stable-baselines3[extra])
  Downloading torch-2.9.1-cp312-cp312-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: cloudpickle in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (3.1.2)
Requirement already satisfied: pandas in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (2.3.3)
Collecting matplotlib (from stable-baselines3[extra])
  Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting opencv-python (from stable-baselines3[extra])
  Downloading opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl.metadata (19 kB)
Collecting pygame (from stable-baselines3[extra])
  Downloading pygame-2.6.1-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting tensorboard>=2.9.1 (from stable-baselines3[extra])
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: psutil in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (7.1.3)
Requirement already satisfied: tqdm in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from stable-baselines3[extra]) (4.67.1)
Collecting rich (from stable-baselines3[extra])
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting ale-py>=0.9.0 (from stable-baselines3[extra])
  Downloading ale_py-0.11.2-cp312-cp312-win_amd64.whl.metadata (9.2 kB)
Collecting pillow (from stable-baselines3[extra])
  Downloading pillow-12.0.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3[extra]) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium<1.3.0,>=0.29.1->stable-baselines3[extra]) (0.0.4)
Collecting filelock (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading filelock-3.20.1-py3-none-any.whl.metadata (2.1 kB)
Collecting sympy>=1.13.3 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable-baselines3[extra]) (3.1.6)
Collecting fsspec>=0.8.5 (from torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading fsspec-2025.12.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from torch<3.0,>=2.3->stable-baselines3[extra]) (80.9.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch<3.0,>=2.3->stable-baselines3[extra])
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting absl-py>=0.4 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting grpcio>=1.48.2 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading grpcio-1.76.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting markdown>=2.6.8 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading markdown-3.10-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: packaging in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (25.0)
Collecting protobuf!=4.24.0,>=3.19.6 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard>=2.9.1->stable-baselines3[extra])
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.1.4)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard>=2.9.1->stable-baselines3[extra]) (3.0.3)
Collecting contourpy>=1.0.1 (from matplotlib->stable-baselines3[extra])
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->stable-baselines3[extra])
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->stable-baselines3[extra])
  Downloading fonttools-4.61.1-cp312-cp312-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->stable-baselines3[extra])
  Downloading kiwisolver-1.4.9-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
Collecting pyparsing>=3 (from matplotlib->stable-baselines3[extra])
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from matplotlib->stable-baselines3[extra]) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3[extra]) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->stable-baselines3[extra]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas->stable-baselines3[extra]) (2025.3)
Collecting markdown-it-py>=2.2.0 (from rich->stable-baselines3[extra])
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from rich->stable-baselines3[extra]) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->stable-baselines3[extra])
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tqdm->stable-baselines3[extra]) (0.4.6)
Downloading stable_baselines3-2.7.1-py3-none-any.whl (188 kB)
Downloading torch-2.9.1-cp312-cp312-win_amd64.whl (110.9 MB)
   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
    --------------------------------------- 1.6/110.9 MB 7.6 MB/s eta 0:00:15
   - -------------------------------------- 3.1/110.9 MB 7.7 MB/s eta 0:00:15
   - -------------------------------------- 4.7/110.9 MB 7.7 MB/s eta 0:00:14
   -- ------------------------------------- 6.6/110.9 MB 7.7 MB/s eta 0:00:14
   --- ------------------------------------ 8.4/110.9 MB 8.0 MB/s eta 0:00:13
   --- ------------------------------------ 10.5/110.9 MB 8.3 MB/s eta 0:00:13
   ---- ----------------------------------- 12.3/110.9 MB 8.3 MB/s eta 0:00:12
   ----- ---------------------------------- 14.4/110.9 MB 8.5 MB/s eta 0:00:12
   ----- ---------------------------------- 16.5/110.9 MB 8.7 MB/s eta 0:00:11
   ------ --------------------------------- 18.9/110.9 MB 9.0 MB/s eta 0:00:11
   ------- -------------------------------- 21.2/110.9 MB 9.1 MB/s eta 0:00:10
   -------- ------------------------------- 23.6/110.9 MB 9.3 MB/s eta 0:00:10
   --------- ------------------------------ 26.2/110.9 MB 9.5 MB/s eta 0:00:09
   ---------- ----------------------------- 28.8/110.9 MB 9.7 MB/s eta 0:00:09
   ----------- ---------------------------- 31.7/110.9 MB 10.0 MB/s eta 0:00:08
   ------------ --------------------------- 34.6/110.9 MB 10.3 MB/s eta 0:00:08
   ------------- -------------------------- 36.4/110.9 MB 10.1 MB/s eta 0:00:08
   ------------- -------------------------- 38.0/110.9 MB 10.0 MB/s eta 0:00:08
   ------------- -------------------------- 38.8/110.9 MB 9.7 MB/s eta 0:00:08
   -------------- ------------------------- 39.6/110.9 MB 9.5 MB/s eta 0:00:08
   -------------- ------------------------- 40.6/110.9 MB 9.1 MB/s eta 0:00:08
   --------------- ------------------------ 41.7/110.9 MB 9.0 MB/s eta 0:00:08
   --------------- ------------------------ 43.0/110.9 MB 8.8 MB/s eta 0:00:08
   --------------- ------------------------ 44.3/110.9 MB 8.7 MB/s eta 0:00:08
   ---------------- ----------------------- 45.6/110.9 MB 8.6 MB/s eta 0:00:08
   ---------------- ----------------------- 46.9/110.9 MB 8.5 MB/s eta 0:00:08
   ----------------- ---------------------- 48.5/110.9 MB 8.5 MB/s eta 0:00:08
   ------------------ --------------------- 50.3/110.9 MB 8.4 MB/s eta 0:00:08
   ------------------ --------------------- 51.9/110.9 MB 8.4 MB/s eta 0:00:08
   ------------------- -------------------- 53.5/110.9 MB 8.4 MB/s eta 0:00:07
   -------------------- ------------------- 55.6/110.9 MB 8.4 MB/s eta 0:00:07
   -------------------- ------------------- 57.4/110.9 MB 8.5 MB/s eta 0:00:07
   --------------------- ------------------ 59.5/110.9 MB 8.5 MB/s eta 0:00:07
   ---------------------- ----------------- 61.6/110.9 MB 8.5 MB/s eta 0:00:06
   ----------------------- ---------------- 64.0/110.9 MB 8.6 MB/s eta 0:00:06
   ----------------------- ---------------- 66.3/110.9 MB 8.7 MB/s eta 0:00:06
   ------------------------ --------------- 68.7/110.9 MB 8.7 MB/s eta 0:00:05
   ------------------------- -------------- 71.0/110.9 MB 8.8 MB/s eta 0:00:05
   -------------------------- ------------- 73.9/110.9 MB 8.9 MB/s eta 0:00:05
   --------------------------- ------------ 76.3/110.9 MB 9.0 MB/s eta 0:00:04
   ---------------------------- ----------- 78.4/110.9 MB 9.0 MB/s eta 0:00:04
   ---------------------------- ----------- 79.7/110.9 MB 9.0 MB/s eta 0:00:04
   ----------------------------- ---------- 80.5/110.9 MB 8.9 MB/s eta 0:00:04
   ----------------------------- ---------- 81.3/110.9 MB 8.7 MB/s eta 0:00:04
   ----------------------------- ---------- 81.8/110.9 MB 8.6 MB/s eta 0:00:04
   ----------------------------- ---------- 82.3/110.9 MB 8.5 MB/s eta 0:00:04
   ----------------------------- ---------- 82.8/110.9 MB 8.4 MB/s eta 0:00:04
   ------------------------------ --------- 83.4/110.9 MB 8.3 MB/s eta 0:00:04
   ------------------------------ --------- 84.1/110.9 MB 8.1 MB/s eta 0:00:04
   ------------------------------ --------- 84.9/110.9 MB 8.0 MB/s eta 0:00:04
   ------------------------------ --------- 85.7/110.9 MB 7.9 MB/s eta 0:00:04
   ------------------------------- -------- 86.8/110.9 MB 7.9 MB/s eta 0:00:04
   ------------------------------- -------- 87.6/110.9 MB 7.8 MB/s eta 0:00:03
   -------------------------------- ------- 88.9/110.9 MB 7.8 MB/s eta 0:00:03
   -------------------------------- ------- 89.9/110.9 MB 7.7 MB/s eta 0:00:03
   -------------------------------- ------- 91.2/110.9 MB 7.7 MB/s eta 0:00:03
   --------------------------------- ------ 92.8/110.9 MB 7.7 MB/s eta 0:00:03
   ---------------------------------- ----- 94.4/110.9 MB 7.7 MB/s eta 0:00:03
   ---------------------------------- ----- 95.9/110.9 MB 7.7 MB/s eta 0:00:02
   ----------------------------------- ---- 97.8/110.9 MB 7.7 MB/s eta 0:00:02
   ----------------------------------- ---- 99.4/110.9 MB 7.7 MB/s eta 0:00:02
   ------------------------------------ --- 101.2/110.9 MB 7.7 MB/s eta 0:00:02
   ------------------------------------- -- 103.3/110.9 MB 7.7 MB/s eta 0:00:01
   ------------------------------------- -- 105.4/110.9 MB 7.8 MB/s eta 0:00:01
   -------------------------------------- - 107.7/110.9 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  109.8/110.9 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  110.9/110.9 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 110.9/110.9 MB 7.7 MB/s  0:00:14
Downloading ale_py-0.11.2-cp312-cp312-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ------------------------ --------------- 2.1/3.5 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 10.8 MB/s  0:00:00
Downloading fsspec-2025.12.0-py3-none-any.whl (201 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 11.6 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   -------------- ------------------------- 2.4/6.3 MB 12.2 MB/s eta 0:00:01
   --------------------------------- ------ 5.2/6.3 MB 12.3 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 12.1 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 8.8 MB/s  0:00:00
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ------------------ --------------------- 2.6/5.5 MB 12.5 MB/s eta 0:00:01
   ------------------------------------ --- 5.0/5.5 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 12.0 MB/s  0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading grpcio-1.76.0-cp312-cp312-win_amd64.whl (4.7 MB)
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   -------------------------- ------------- 3.1/4.7 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 4.7/4.7 MB 14.2 MB/s  0:00:00
Downloading markdown-3.10-py3-none-any.whl (107 kB)
Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl (436 kB)
Downloading filelock-3.20.1-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --------------- ------------------------ 3.1/8.1 MB 14.2 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.1 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 12.9 MB/s  0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 16.5 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp312-cp312-win_amd64.whl (73 kB)
Downloading pillow-12.0.0-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   -------------------- ------------------- 3.7/7.0 MB 16.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.0 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 15.4 MB/s  0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Downloading opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl (39.0 MB)
   ---------------------------------------- 0.0/39.0 MB ? eta -:--:--
   --- ------------------------------------ 3.1/39.0 MB 15.4 MB/s eta 0:00:03
   ------ --------------------------------- 6.6/39.0 MB 15.5 MB/s eta 0:00:03
   ----------- ---------------------------- 10.7/39.0 MB 16.8 MB/s eta 0:00:02
   -------------- ------------------------- 14.4/39.0 MB 16.8 MB/s eta 0:00:02
   ----------------- ---------------------- 16.8/39.0 MB 15.8 MB/s eta 0:00:02
   -------------------- ------------------- 19.7/39.0 MB 15.5 MB/s eta 0:00:02
   ----------------------- ---------------- 22.5/39.0 MB 15.2 MB/s eta 0:00:02
   -------------------------- ------------- 25.7/39.0 MB 15.2 MB/s eta 0:00:01
   ----------------------------- ---------- 29.1/39.0 MB 15.2 MB/s eta 0:00:01
   --------------------------------- ------ 32.5/39.0 MB 15.4 MB/s eta 0:00:01
   ------------------------------------- -- 36.4/39.0 MB 15.5 MB/s eta 0:00:01
   ---------------------------------------  38.8/39.0 MB 15.7 MB/s eta 0:00:01
   ---------------------------------------- 39.0/39.0 MB 15.1 MB/s  0:00:02
Downloading pygame-2.6.1-cp312-cp312-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ------------- -------------------------- 3.7/10.6 MB 16.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.6/10.6 MB 18.1 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 17.0 MB/s  0:00:00
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: mpmath, tensorboard-data-server, sympy, pyparsing, pygame, protobuf, pillow, opencv-python, networkx, mdurl, markdown, kiwisolver, grpcio, fsspec, fonttools, filelock, cycler, contourpy, ale-py, absl-py, torch, tensorboard, matplotlib, markdown-it-py, stable-baselines3, rich

   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   ----------------------------------------  0/26 [mpmath]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]
   --- ------------------------------------  2/26 [sympy]

In [13]:
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.env_checker import check_env

#print(check_env(env=env))

#vec_env = make_vec_env(env, n_envs=4)

model = PPO("MlpPolicy",env)

model.learn(total_timesteps=250000)
model.save("PPO_test1")

Market Return : 677.81%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return :  5.27%   |   Portfolio Return : -95.75%   |   Portfolio Valuation : 42.47   |
Market Return : 103.26%   |   Portfolio Return : -80.38%   |   Portfolio Valuation : 196.22   |
Market Return : 10.54%   |   Portfolio Return : -23.62%   |   Portfolio Valuation : 763.82   |
Market Return : 27.70%   |   Portfolio Return : -30.06%   |   Portfolio Valuation : 699.35   |
Market Return : 590.66%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : -0.02   |
Market Return : 39.94%   |   Portfolio Return : -14.62%   |   Portfolio Valuation : 853.82   |
Market Return : 279.25%   |   Portfolio Return : -100.03%   |   Portfolio Valuation : -0.3   |
Market Return : 44.45%   |   Portfolio Return : -27.32%   |   Portfolio Valuation : 726.77   |
Market Return : 39.94%   |   Portfolio Return : -47.66%   |   Portfolio Valuation : 523.36   |
Market Return : 27.70%   |   Portfolio Return :  3.41%   |   Portfolio Valuation : 1034.13   |
Market Return : 83.90%   |   Portfolio Return : -102.69%   |   Portfolio Valuation : -26.93   |
Market Return : 103.26%   |   Portfolio Return : -55.57%   |   Portfolio Valuation : 444.31   |
Market Return : 10.54%   |   Portfolio Return : -10.43%   |   Portfolio Valuation : 895.65   |
Market Return : 44.45%   |   Portfolio Return : -33.02%   |   Portfolio Valuation : 669.76   |
Market Return :  5.27%   |   Portfolio Return : -5.69%   |   Portfolio Valuation : 943.13   |
Market Return : 364.35%   |   Portfolio Return : -100.06%   |   Portfolio Valuation : -0.57   |
Market Return : 221.18%   |   Portfolio Return : -100.69%   |   Portfolio Valuation : -6.94   |
Market Return : 10.54%   |   Portfolio Return : -3.86%   |   Portfolio Valuation : 961.4   |
Market Return : 44.45%   |   Portfolio Return : -39.65%   |   Portfolio Valuation : 603.52   |
Market Return : 12.62%   |   Portfolio Return : -104.28%   |   Portfolio Valuation : -42.85   |

In [ ]:
i=0
obs,_ = env.reset()
while i<100:
    i+=1
    action, _states = model.predict(obs)
    print(action)
    obs, reward, terminated, truncated, info = env.step(action)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [14]:
nb_episodes = 3

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)


for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
    env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 95.06%   |   Portfolio Return : -101.35%   |   Portfolio Valuation : -13.46   |
Argent perdu
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.94%   |   Portfolio Return : -45.77%   |   Portfolio Valuation : 542.28   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.27%   |   Portfolio Return : -6.77%   |   Portfolio Valuation : 932.32   |
Épisode terminé

In [67]:
env.historical_info[-1]

{'idx': 2763,
 'step': 2763,
 'date': np.datetime64('2025-06-25T13:30:00.000000000'),
 'position_index': array(1),
 'position': 1,
 'real_position': np.float64(1.0000000000000002),
 'data_date_close': Timestamp('2025-06-25 14:30:00'),
 'data_close': 6100.830078125,
 'data_high': 6108.509765625,
 'data_volume': 0,
 'data_open': 6104.22998046875,
 'data_low': 6096.8798828125,
 'portfolio_valuation': np.float64(1346.3183462273655),
 'portfolio_distribution_asset': np.float64(0.22067789612018449),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': np.float64(1.1368683772161603e-13),
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': np.float64(9.473903143468003e-19),
 'reward': np.float64(0.0012383509773613998)}

Actuellement, les résultats sont trop aléatoirs, parfois l'agent apprend rapidement mais il n'est pas enclin à faire mieux que le marché. Il se contente de toujours garder son argent.
Nous allons améliorer notre programme de 2 manières:
    - Changer la fonction de reward, pour qu'elle récompense plus l'exploration
    - ajouter des features pour que l'agent comprenne mieux le marché

In [112]:
env.env.historical_info[-1]

{'idx': 42131,
 'step': 42131,
 'date': np.datetime64('2025-11-20T13:00:00.000000000'),
 'position_index': 13,
 'position': 1.4,
 'real_position': np.float64(1.398325122244509),
 'data_high': 0.13837,
 'data_low': 0.13651,
 'data_open': 0.13783,
 'data_date_close': Timestamp('2025-11-20 14:00:00'),
 'data_volume': 445127.0,
 'data_close': 0.13673,
 'portfolio_valuation': np.float64(1654.837230888517),
 'portfolio_distribution_asset': np.float64(16923.86801124077),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': np.float64(659.1577493071892),
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': np.float64(0.0054929812442265765),
 'reward': np.float64(-0.00355254135303337)}

In [104]:
def preprocess_v2(df):
    df = df.sort_index()
    df = df.dropna()
    df = df.drop_duplicates()

    # Valeur des différentes features par rapport à la moyenne
    df['feature_close'] = (df['close'] - df['close'].mean()) / df['close'].std()
    df['feature_high'] = (df['high'] - df['high'].mean()) / df['high'].std()
    df['feature_low'] = (df['low'] - df['low'].mean()) / df['low'].std()

    #Valeur des ratios entre 2 des 4 niveaux (haut/bas ou fermeture/ouverture)
    df['feature_ratio_high_low'] = (df['high'] / df['low'])
    df['feature_ratio_close_open'] = (df['close'] / df['open'])
    df['feature_ratio_high_close'] = (df['high'] / df['close'])

    #Valeur des features par rapport à leur max
    df['feature_max_ratio_close'] = (df['close'] - df['close'].max()) / df['close'].max()
    df['feature_max_ratio_open'] = (df['open'] - df['open'].max()) / df['open'].max()
    df['feature_max_ratio_low'] = (df['low'] - df['low'].max()) / df['low'].max()
    df['feature_max_ratio_high'] = (df['high'] - df['high'].max()) / df['high'].max()

    #Valeur des ratios par rapport à leur max entre 2 des 4 niveaux (haut/bas ou fermeture/ouverture)
    df['feature_ratio_max_high_low'] = (df['feature_ratio_high_low'] - df['feature_ratio_high_low'].max()) / df['feature_ratio_high_low'].max()
    df['feature_ratio_max__close_open'] = (df['feature_ratio_close_open'] - df['feature_ratio_close_open'].max()) / df['feature_ratio_close_open'].max()
    df['feature_ratio_max_high_close'] = (df['feature_ratio_high_close'] - df['feature_ratio_high_close'].max()) / df['feature_ratio_high_close'].max()

    return df

df = preprocess_v2(pd.read_pickle('./data/yfinance-AAPL-1h.pkl'))
df.head(5)

,open,high,low,close,volume,date_close,feature_close,feature_high,feature_low,feature_ratio_high_low,feature_ratio_close_open,feature_ratio_high_close,feature_max_ratio_close,feature_max_ratio_open,feature_max_ratio_low,feature_max_ratio_high,feature_ratio_max_high_low,feature_ratio_max__close_open,feature_ratio_max_high_close
date_open,,,,,,,,,,,,,,,,,,,
2023-11-21 14:30:00,191.410004,191.520004,190.270004,190.347504,8992766,2023-11-21 15:30:00,-0.953609,-0.934171,-0.930512,1.006570,0.994449,1.006160,-0.309597,-0.308964,-0.308235,-0.309390,-0.094637,-0.052735,-0.054685
2023-11-21 15:30:00,190.350006,190.470001,189.740005,189.942001,5681421,2023-11-21 16:30:00,-0.969213,-0.974486,-0.950975,1.003847,0.997857,1.002780,-0.311068,-0.312791,-0.310162,-0.313176,-0.097086,-0.049490,-0.057860
2023-11-21 16:30:00,189.940002,190.320007,189.830002,190.274994,3359800,2023-11-21 17:30:00,-0.956399,-0.980244,-0.947501,1.002581,1.001764,1.000237,-0.309860,-0.314271,-0.309835,-0.313717,-0.098224,-0.045768,-0.060250
2023-11-21 17:30:00,190.276993,190.600006,190.039993,190.119995,3112369,2023-11-21 18:30:00,-0.962363,-0.969494,-0.939393,1.002947,0.999175,1.002525,-0.310422,-0.313055,-0.309071,-0.312707,-0.097895,-0.048234,-0.058100
2023-11-21 18:30:00,190.119995,190.615005,190.085007,190.380005,2874142,2023-11-21 19:30:00,-0.952358,-0.968918,-0.937655,1.002788,1.001368,1.001234,-0.309479,-0.313621,-0.308907,-0.312653,-0.098038,-0.046145,-0.059312

In [6]:
from gym_trading_env.wrapper import DiscreteActionsWrapper

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 


env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_v2,
    reward_function=reward_function_rapport_market,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.5,0.6,0.8,1,1.2,1.4,1.6,1.8,2])
obs, _ = env.reset()

ModuleNotFoundError: No module named 'gym_trading_env.wrapper'

In [125]:
from stable_baselines3 import PPO

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=300_000)

Market Return : 39.94%   |   Portfolio Return : -97.79%   |   Portfolio Valuation : 22.14   |
Market Return :  5.27%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.01   |
Market Return : 163.91%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return : 904.05%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return : 10.54%   |   Portfolio Return : -59.97%   |   Portfolio Valuation : 400.28   |
Market Return : 677.81%   |   Portfolio Return : -99.96%   |   Portfolio Valuation : 0.4   |
Market Return : 27.70%   |   Portfolio Return : -36.32%   |   Portfolio Valuation : 636.84   |
Market Return : 10.54%   |   Portfolio Return : -16.43%   |   Portfolio Valuation : 835.73   |
Market Return : 904.05%   |   Portfolio Return : 745.66%   |   Portfolio Valuation : 8456.63   |
Market Return :  5.27%   |   Portfolio Return : -89.92%   |   Portfolio Valuation : 100.82   |
Market Return : 39.94%   |   Portfolio Return : -28.13%   |   Portfolio Valuation : 718.7   |
Market Return : 44.45%   |   Portfolio Return : -48.28%   |   Portfolio Valuation : 517.16   |
Market Return : 677.81%   |   Portfolio Return : -99.76%   |   Portfolio Valuation : 2.39   |

In [127]:
nb_episodes = 10

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 27.70%   |   Portfolio Return : -38.70%   |   Portfolio Valuation : 612.98   |
Épisode terminé
Episode n˚2 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 163.91%   |   Portfolio Return : -57.81%   |   Portfolio Valuation : 421.9   |
Épisode terminé
Episode n˚3 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 904.05%   |   Portfolio Return : -96.30%   |   Portfolio Valuation : 36.96   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 44.45%   |   Portfolio Return : -8.39%   |   Portfolio Valuation : 916.08   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.27%   |   Portfolio Return : -88.12%   |   Portfolio Valuation : 118.85   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 27.70%   |   Portfolio Return : -28.74%   |   Portfolio Valuation : 712.57   |
Épisode terminé
Episode n˚7 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.26%   |   Portfolio Return : -76.53%   |   Portfolio Valuation : 234.69   |
Épisode terminé
Episode n˚8 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.94%   |   Portfolio Return : 10.65%   |   Portfolio Valuation : 1106.5   |
Épisode terminé
Episode n˚9 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 677.81%   |   Portfolio Return : -98.26%   |   Portfolio Valuation : 17.45   |
Épisode terminé
Episode n˚10 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return : 10.54%   |   Portfolio Return : -35.47%   |   Portfolio Valuation : 645.28   |
Épisode terminé

In [81]:
env.env.historical_info[-1]

{'idx': 4509,
 'step': 4509,
 'date': np.datetime64('2025-11-21T13:00:00.000000000'),
 'position_index': 4,
 'position': 1,
 'real_position': np.float64(1.0),
 'data_high': 5531.83984375,
 'data_open': 5525.81982421875,
 'data_low': 5518.8798828125,
 'data_volume': 0,
 'data_delta_high_low': 1.002348295526029,
 'data_delta_open_close': 1.0009030758391957,
 'data_date_close': Timestamp('2025-11-21 14:00:00'),
 'data_close': 5530.81005859375,
 'portfolio_valuation': np.float64(1121.6929142246133),
 'portfolio_distribution_asset': np.float64(0.20280807012740049),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': 0,
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': 0.0,
 'reward': np.float64(-6.340988893560606e-05)}

In [1]:
!pip install pandas_ta

Collecting pandas_ta
  Using cached pandas_ta-0.4.71b0-py3-none-any.whl.metadata (2.3 kB)
Collecting numba==0.61.2 (from pandas_ta)
  Using cached numba-0.61.2-cp312-cp312-win_amd64.whl.metadata (2.9 kB)
Requirement already satisfied: numpy>=2.2.6 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas_ta) (2.3.5)
Requirement already satisfied: pandas>=2.3.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas_ta) (2.3.3)
Collecting tqdm>=4.67.1 (from pandas_ta)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba==0.61.2->pandas_ta)
  Using cached llvmlite-0.44.0-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Collecting numpy>=2.2.6 (from pandas_ta)
  Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=2.3.2->pandas_ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=2.3.2->pandas_ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=2.3.2->pandas_ta) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.3.2->pandas_ta) (1.17.0)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from tqdm>=4.67.1->pandas_ta) (0.4.6)
Using cached pandas_ta-0.4.71b0-py3-none-any.whl (240 kB)
Using cached numba-0.61.2-cp312-cp312-win_amd64.whl (2.8 MB)
Using cached llvmlite-0.44.0-cp312-cp312-win_amd64.whl (30.3 MB)
Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl (12.6 MB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, numpy, llvmlite, numba, pandas_ta

   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
  Attempting uninstall: numpy
   ---------------------------------------- 0/5 [tqdm]
    Found existing installation: numpy 2.3.5
   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [numpy]
    Uninstalling numpy-2.3.5:
   -------- ------------------------------- 1/5 [numpy]
      Successfully uninstalled numpy-2.3.5
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ---------------- ----------------------- 2/5 [llvmlite]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   ------------------------ --------------- 3/5 [numba]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   -------------------------------- ------- 4/5 [pandas_ta]
   ---------------------------------------- 5/5 [pandas_ta]

Successfully installed llvmlite-0.44.0 numba-0.61.2 numpy-2.2.6 pandas_ta-0.4.71b0 tqdm-4.67.1

In [2]:
pip install --upgrade pip

Requirement already satisfied: pip in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (25.3)
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install gym-trading-env-continuous

Collecting gym-trading-env-continuous
  Using cached gym_trading_env_continuous-1.0.3-py3-none-any.whl.metadata (4.9 kB)
Collecting pandas>=1.5.3 (from gym-trading-env-continuous)
  Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.21.1 (from gym-trading-env-continuous)
  Using cached numpy-2.3.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting gymnasium>=0.28.1 (from gym-trading-env-continuous)
  Using cached gymnasium-1.2.2-py3-none-any.whl.metadata (10 kB)
Collecting flask>=2.2.3 (from gym-trading-env-continuous)
  Downloading flask-3.1.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyecharts>=2.0.2 (from gym-trading-env-continuous)
  Using cached pyecharts-2.0.9-py3-none-any.whl.metadata (1.6 kB)
Collecting ccxt==3.0.59 (from gym-trading-env-continuous)
  Using cached ccxt-3.0.59-py2.py3-none-any.whl.metadata (111 kB)
Requirement already satisfied: nest_asyncio in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym-trading-env-continuous) (1.6.0)
Collecting setuptools>=60.9.0 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2018.1.18 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Collecting requests>=2.18.4 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting cryptography>=2.6.1 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached cryptography-46.0.3-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting aiohttp>=3.8 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiohttp-3.13.2-cp312-cp312-win_amd64.whl.metadata (8.4 kB)
Collecting aiodns>=1.1.1 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiodns-3.6.1-py3-none-any.whl.metadata (5.8 kB)
Collecting yarl>=1.7.2 (from ccxt==3.0.59->gym-trading-env-continuous)
  Using cached yarl-1.22.0-cp312-cp312-win_amd64.whl.metadata (77 kB)
Collecting pycares<5,>=4.9.0 (from aiodns>=1.1.1->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached pycares-4.11.0-cp312-cp312-win_amd64.whl.metadata (4.8 kB)
Collecting cffi>=1.5.0 (from pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached multidict-6.7.0-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached propcache-0.4.1-cp312-cp312-win_amd64.whl.metadata (14 kB)
Collecting idna>=2.0 (from yarl>=1.7.2->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting typing-extensions>=4.2 (from aiosignal>=1.4.0->aiohttp>=3.8->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pycparser (from cffi>=1.5.0->pycares<5,>=4.9.0->aiodns>=1.1.1->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached pycparser-2.23-py3-none-any.whl.metadata (993 bytes)
Collecting blinker>=1.9.0 (from flask>=2.2.3->gym-trading-env-continuous)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click>=8.1.3 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting itsdangerous>=2.2.0 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting werkzeug>=3.1.0 (from flask>=2.2.3->gym-trading-env-continuous)
  Using cached werkzeug-3.1.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from click>=8.1.3->flask>=2.2.3->gym-trading-env-continuous) (0.4.6)
Collecting cloudpickle>=1.2.0 (from gymnasium>=0.28.1->gym-trading-env-continuous)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting farama-notifications>=0.0.1 (from gymnasium>=0.28.1->gym-trading-env-continuous)
  Using cached Farama_Notifications-0.0.4-py3-none-any.whl.metadata (558 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym-trading-env-continuous) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas>=1.5.3->gym-trading-env-continuous)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=1.5.3->gym-trading-env-continuous)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting prettytable (from pyecharts>=2.0.2->gym-trading-env-continuous)
  Using cached prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting simplejson (from pyecharts>=2.0.2->gym-trading-env-continuous)
  Using cached simplejson-3.20.2-cp312-cp312-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->gym-trading-env-continuous) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests>=2.18.4->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl.metadata (38 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.18.4->ccxt==3.0.59->gym-trading-env-continuous)
  Using cached urllib3-2.6.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: wcwidth in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from prettytable->pyecharts>=2.0.2->gym-trading-env-continuous) (0.2.14)
Using cached gym_trading_env_continuous-1.0.3-py3-none-any.whl (18 kB)
Using cached ccxt-3.0.59-py2.py3-none-any.whl (3.6 MB)
Using cached aiodns-3.6.1-py3-none-any.whl (8.0 kB)
Using cached pycares-4.11.0-cp312-cp312-win_amd64.whl (144 kB)
Using cached aiohttp-3.13.2-cp312-cp312-win_amd64.whl (453 kB)
Using cached multidict-6.7.0-cp312-cp312-win_amd64.whl (46 kB)
Using cached yarl-1.22.0-cp312-cp312-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Using cached certifi-2025.11.12-py3-none-any.whl (159 kB)
Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl (183 kB)
Using cached cryptography-46.0.3-cp311-abi3-win_amd64.whl (3.5 MB)
Downloading flask-3.1.2-py3-none-any.whl (103 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Using cached frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
Using cached gymnasium-1.2.2-py3-none-any.whl (952 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached Farama_Notifications-0.0.4-py3-none-any.whl (2.5 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Using cached numpy-2.3.5-cp312-cp312-win_amd64.whl (12.8 MB)
Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
Using cached propcache-0.4.1-cp312-cp312-win_amd64.whl (41 kB)
Using cached pyecharts-2.0.9-py3-none-any.whl (153 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl (107 kB)
Using cached urllib3-2.6.2-py3-none-any.whl (131 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Using cached werkzeug-3.1.4-py3-none-any.whl (224 kB)
Using cached prettytable-3.17.0-py3-none-any.whl (34 kB)
Using cached pycparser-2.23-py3-none-any.whl (118 kB)
Using cached simplejson-3.20.2-cp312-cp312-win_amd64.whl (75 kB)
Installing collected packages: pytz, farama-notifications, urllib3, tzdata, typing-extensions, simplejson, setuptools, pycparser, propcache, prettytable, numpy, multidict, markupsafe, itsdangerous, idna, frozenlist, cloudpickle, click, charset_normalizer, certifi, blinker, attrs, aiohappyeyeballs, yarl, werkzeug, requests, pandas, jinja2, gymnasium, cffi, aiosignal, pyecharts, pycares, flask, cryptography, aiohttp, aiodns, ccxt, gym-trading-env-continuous

   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   ----------------------------------------  0/39 [pytz]
   - --------------------------------------  1/39 [farama-notifications]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   -- -------------------------------------  2/39 [urllib3]
   --- ------------------------------------  3/39 [tzdata]
   --- ------------------------------------  3/39 [tzdata]
   --- ------------------------------------  3/39 [tzdata]
   --- ------------------------------------  3/39 [tzdata]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ----- ----------------------------------  5/39 [simplejson]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------ ---------------------------------  6/39 [setuptools]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   ------- --------------------------------  7/39 [pycparser]
   -------- -------------------------------  8/39 [propcache]
   --------- ------------------------------  9/39 [prettytable]
   --------- ------------------------------  9/39 [prettytable]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]
   ---------- ----------------------------- 10/39 [numpy]

In [6]:
import pandas_ta as ta
import numpy as np

def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df

In [7]:
from gym_trading_env.wrapper import DiscreteActionsWrapper

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_log_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-1, 0, 1])
obs, _ = env.reset()

In [8]:
from stable_baselines3 import PPO

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=1_000_000)

Market Return : 26.58%   |   Portfolio Return : -97.66%   |   Portfolio Valuation : 23.42   |
Market Return : 946.44%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return :  9.40%   |   Portfolio Return : -23.17%   |   Portfolio Valuation : 768.3   |
Market Return : 103.53%   |   Portfolio Return : 33.01%   |   Portfolio Valuation : 1330.08   |
Market Return :  5.93%   |   Portfolio Return : -2.23%   |   Portfolio Valuation : 977.66   |
Market Return : 43.37%   |   Portfolio Return : 39.13%   |   Portfolio Valuation : 1391.26   |
Market Return : 376.91%   |   Portfolio Return : 232.39%   |   Portfolio Valuation : 3323.86   |
Market Return : 43.37%   |   Portfolio Return : 40.84%   |   Portfolio Valuation : 1408.4   |
Market Return : 946.44%   |   Portfolio Return : 378.04%   |   Portfolio Valuation : 4780.42   |
Market Return : 699.62%   |   Portfolio Return : -68.27%   |   Portfolio Valuation : 317.3   |
Market Return : 103.53%   |   Portfolio Return : 86.52%   |   Portfolio Valuation : 1865.16   |
Market Return :  5.93%   |   Portfolio Return :  3.71%   |   Portfolio Valuation : 1037.07   |
Market Return : 26.58%   |   Portfolio Return : 26.54%   |   Portfolio Valuation : 1265.36   |
Market Return :  9.40%   |   Portfolio Return :  9.35%   |   Portfolio Valuation : 1093.54   |
Market Return : 553.19%   |   Portfolio Return : -104.82%   |   Portfolio Valuation : -48.21   |
Market Return : 39.77%   |   Portfolio Return : -11.87%   |   Portfolio Valuation : 881.26   |
Market Return :  9.40%   |   Portfolio Return : -53.59%   |   Portfolio Valuation : 464.1   |
Market Return : 43.37%   |   Portfolio Return : 21.76%   |   Portfolio Valuation : 1217.61   |
Market Return : 699.62%   |   Portfolio Return : -64.81%   |   Portfolio Valuation : 351.88   |
Market Return :  5.93%   |   Portfolio Return :  5.18%   |   Portfolio Valuation : 1051.84   |
Market Return : 376.91%   |   Portfolio Return : 325.32%   |   Portfolio Valuation : 4253.18   |
Market Return : 39.77%   |   Portfolio Return : 26.98%   |   Portfolio Valuation : 1269.77   |
Market Return : 26.58%   |   Portfolio Return : -12.56%   |   Portfolio Valuation : 874.37   |
Market Return : 103.53%   |   Portfolio Return : -46.77%   |   Portfolio Valuation : 532.28   |
Market Return : 946.44%   |   Portfolio Return : -92.83%   |   Portfolio Valuation : 71.68   |
Market Return : 376.91%   |   Portfolio Return : -76.56%   |   Portfolio Valuation : 234.37   |
Market Return :  5.93%   |   Portfolio Return : -63.18%   |   Portfolio Valuation : 368.24   |
Market Return : 103.53%   |   Portfolio Return : -37.26%   |   Portfolio Valuation : 627.38   |
Market Return : 699.62%   |   Portfolio Return : -94.71%   |   Portfolio Valuation : 52.85   |
Market Return :  9.40%   |   Portfolio Return : -2.52%   |   Portfolio Valuation : 974.82   |
Market Return : 946.44%   |   Portfolio Return : -87.11%   |   Portfolio Valuation : 128.94   |
Market Return : 26.58%   |   Portfolio Return : -0.57%   |   Portfolio Valuation : 994.29   |
Market Return : 43.37%   |   Portfolio Return : -49.59%   |   Portfolio Valuation : 504.08   |
Market Return : 39.77%   |   Portfolio Return : -46.02%   |   Portfolio Valuation : 539.79   |
Market Return : 946.44%   |   Portfolio Return : -87.30%   |   Portfolio Valuation : 126.99   |
Market Return : 376.91%   |   Portfolio Return : 12.27%   |   Portfolio Valuation : 1122.73   |
Market Return : 43.37%   |   Portfolio Return : -49.95%   |   Portfolio Valuation : 500.53   |
Market Return :  9.40%   |   Portfolio Return : -35.16%   |   Portfolio Valuation : 648.37   |
Market Return : 39.77%   |   Portfolio Return : -49.09%   |   Portfolio Valuation : 509.14   |
Market Return : 26.58%   |   Portfolio Return : -25.68%   |   Portfolio Valuation : 743.22   |
Market Return : 103.53%   |   Portfolio Return : -49.10%   |   Portfolio Valuation : 509.05   |
Market Return : 699.62%   |   Portfolio Return : -95.68%   |   Portfolio Valuation : 43.22   |
Market Return :  5.93%   |   Portfolio Return : -63.25%   |   Portfolio Valuation : 367.51   |
Market Return : 39.77%   |   Portfolio Return : -50.18%   |   Portfolio Valuation : 498.23   |
Market Return :  5.93%   |   Portfolio Return : -62.93%   |   Portfolio Valuation : 370.7   |
Market Return : 376.91%   |   Portfolio Return : 175.77%   |   Portfolio Valuation : 2757.74   |
Market Return : 43.37%   |   Portfolio Return : -48.77%   |   Portfolio Valuation : 512.26   |
Market Return :  9.40%   |   Portfolio Return : -46.75%   |   Portfolio Valuation : 532.47   |
Market Return : 946.44%   |   Portfolio Return : -99.90%   |   Portfolio Valuation : 0.95   |
Market Return : 103.53%   |   Portfolio Return : -76.37%   |   Portfolio Valuation : 236.29   |
Market Return : 699.62%   |   Portfolio Return : -98.53%   |   Portfolio Valuation : 14.7   |
Market Return : 26.58%   |   Portfolio Return : -6.75%   |   Portfolio Valuation : 932.46   |

In [9]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.21%   |   Portfolio Valuation : 537.92   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -43.29%   |   Portfolio Valuation : 567.1   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return :  0.13%   |   Portfolio Valuation : 1001.33   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -36.63%   |   Portfolio Valuation : 633.72   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -61.87%   |   Portfolio Valuation : 381.25   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -3.97%   |   Portfolio Valuation : 960.33   |
Épisode terminé
Episode n˚7 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 165.03%   |   Portfolio Valuation : 2650.32   |
Épisode terminé
Episode n˚8 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -92.13%   |   Portfolio Valuation : 78.74   |
Épisode terminé
Episode n˚9 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -87.68%   |   Portfolio Valuation : 123.21   |
Épisode terminé
Episode n˚10 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -61.43%   |   Portfolio Valuation : 385.73   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -36.38%   |   Portfolio Valuation : 636.2   |
Épisode terminé
Episode n˚12 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -2.56%   |   Portfolio Valuation : 974.38   |
Épisode terminé
Episode n˚13 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -43.98%   |   Portfolio Valuation : 560.17   |
Épisode terminé
Episode n˚14 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -91.70%   |   Portfolio Valuation : 82.99   |
Épisode terminé
Episode n˚15 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.59%   |   Portfolio Valuation : 534.11   |
Épisode terminé
Episode n˚16 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 332.39%   |   Portfolio Valuation : 4323.86   |
Épisode terminé
Episode n˚17 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -2.82%   |   Portfolio Valuation : 971.79   |
Épisode terminé
Episode n˚18 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -89.20%   |   Portfolio Valuation : 107.95   |
Épisode terminé
Episode n˚19 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 946.44%   |   Portfolio Return : -88.01%   |   Portfolio Valuation : 119.85   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -61.20%   |   Portfolio Valuation : 387.95   |
Épisode terminé
Episode n˚21 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 376.91%   |   Portfolio Return : 128.91%   |   Portfolio Valuation : 2289.09   |
Épisode terminé
Episode n˚22 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -1.99%   |   Portfolio Valuation : 980.14   |
Épisode terminé
Episode n˚23 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.83%   |   Portfolio Valuation : 531.66   |
Épisode terminé
Episode n˚24 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : -37.83%   |   Portfolio Valuation : 621.71   |
Épisode terminé
Episode n˚25 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -44.11%   |   Portfolio Valuation : 558.87   |
Épisode terminé
Episode n˚26 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -1.20%   |   Portfolio Valuation : 988.0   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : -2.78%   |   Portfolio Valuation : 972.18   |
Épisode terminé
Episode n˚28 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : -46.29%   |   Portfolio Valuation : 537.11   |
Épisode terminé
Episode n˚29 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 699.62%   |   Portfolio Return : -92.28%   |   Portfolio Valuation : 77.2   |
Épisode terminé
Episode n˚30 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : -46.63%   |   Portfolio Valuation : 533.69   |
Épisode terminé

In [12]:
def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-1, 0, 0.5, 1,2])
obs, _ = env.reset()

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=1_500_000)

Market Return : 43.37%   |   Portfolio Return : -97.53%   |   Portfolio Valuation : 24.66   |
Market Return : 26.58%   |   Portfolio Return : -98.95%   |   Portfolio Valuation : 10.5   |
Market Return :  9.40%   |   Portfolio Return : -98.34%   |   Portfolio Valuation : 16.62   |
Market Return : 39.77%   |   Portfolio Return : -95.20%   |   Portfolio Valuation : 47.96   |
Market Return : 103.53%   |   Portfolio Return : -99.82%   |   Portfolio Valuation : 1.79   |
Market Return : 946.44%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.01   |
Market Return :  5.93%   |   Portfolio Return : -54.17%   |   Portfolio Valuation : 458.28   |
Market Return : 39.77%   |   Portfolio Return : 76.58%   |   Portfolio Valuation : 1765.76   |
Market Return : 351.97%   |   Portfolio Return : -100.70%   |   Portfolio Valuation : -7.04   |
Market Return : 26.58%   |   Portfolio Return : 47.12%   |   Portfolio Valuation : 1471.24   |
Market Return :  5.93%   |   Portfolio Return :  9.70%   |   Portfolio Valuation : 1096.96   |
Market Return :  9.40%   |   Portfolio Return : 18.63%   |   Portfolio Valuation : 1186.3   |
Market Return : 699.62%   |   Portfolio Return : 2172.11%   |   Portfolio Valuation : 22721.14   |
Market Return : 43.37%   |   Portfolio Return : 86.51%   |   Portfolio Valuation : 1865.11   |
Market Return : 223.70%   |   Portfolio Return : -114.55%   |   Portfolio Valuation : -145.52   |
Market Return : 103.53%   |   Portfolio Return : 261.69%   |   Portfolio Valuation : 3616.91   |
Market Return : 235.14%   |   Portfolio Return : -115.22%   |   Portfolio Valuation : -152.25   |
Market Return : 39.77%   |   Portfolio Return : 76.14%   |   Portfolio Valuation : 1761.42   |
Market Return :  9.40%   |   Portfolio Return : 14.50%   |   Portfolio Valuation : 1144.98   |
Market Return : 26.58%   |   Portfolio Return : 55.59%   |   Portfolio Valuation : 1555.89   |
Market Return : 699.62%   |   Portfolio Return : 116.12%   |   Portfolio Valuation : 2161.21   |
Market Return : 43.37%   |   Portfolio Return : 96.64%   |   Portfolio Valuation : 1966.38   |
Market Return : 103.53%   |   Portfolio Return : 153.58%   |   Portfolio Valuation : 2535.79   |
Market Return : 504.01%   |   Portfolio Return : -102.74%   |   Portfolio Valuation : -27.37   |
Market Return :  5.93%   |   Portfolio Return : -39.08%   |   Portfolio Valuation : 609.24   |
Market Return : 43.37%   |   Portfolio Return : 91.46%   |   Portfolio Valuation : 1914.59   |
Market Return :  9.40%   |   Portfolio Return : 15.38%   |   Portfolio Valuation : 1153.76   |
Market Return : 39.77%   |   Portfolio Return : 81.51%   |   Portfolio Valuation : 1815.13   |
Market Return :  5.93%   |   Portfolio Return :  8.60%   |   Portfolio Valuation : 1085.98   |
Market Return : 497.35%   |   Portfolio Return : -147.90%   |   Portfolio Valuation : -478.97   |
Market Return : 103.53%   |   Portfolio Return : 158.19%   |   Portfolio Valuation : 2581.86   |
Market Return : 392.20%   |   Portfolio Return : -274.01%   |   Portfolio Valuation : -1740.13   |
Market Return : 175.57%   |   Portfolio Return : -105.17%   |   Portfolio Valuation : -51.75   |
Market Return : 26.58%   |   Portfolio Return : 52.88%   |   Portfolio Valuation : 1528.79   |
Market Return :  9.40%   |   Portfolio Return : 18.72%   |   Portfolio Valuation : 1187.24   |
Market Return :  5.93%   |   Portfolio Return : -43.87%   |   Portfolio Valuation : 561.34   |
Market Return : 39.77%   |   Portfolio Return : 86.71%   |   Portfolio Valuation : 1867.06   |
Market Return : 103.53%   |   Portfolio Return : 196.44%   |   Portfolio Valuation : 2964.35   |
Market Return : 497.35%   |   Portfolio Return : -118.17%   |   Portfolio Valuation : -181.72   |
Market Return : 26.58%   |   Portfolio Return : 51.44%   |   Portfolio Valuation : 1514.39   |
Market Return : 43.37%   |   Portfolio Return : 92.54%   |   Portfolio Valuation : 1925.37   |
Market Return : 317.93%   |   Portfolio Return : -138.40%   |   Portfolio Valuation : -384.04   |
Market Return : 699.62%   |   Portfolio Return : -6.32%   |   Portfolio Valuation : 936.84   |
Market Return : 504.01%   |   Portfolio Return : -120.19%   |   Portfolio Valuation : -201.91   |
Market Return : 699.62%   |   Portfolio Return : 404.60%   |   Portfolio Valuation : 5045.97   |
Market Return : 103.53%   |   Portfolio Return : 259.82%   |   Portfolio Valuation : 3598.22   |
Market Return : 334.02%   |   Portfolio Return : -165.61%   |   Portfolio Valuation : -656.06   |
Market Return :  9.40%   |   Portfolio Return : 14.99%   |   Portfolio Valuation : 1149.85   |
Market Return :  5.93%   |   Portfolio Return : -1.71%   |   Portfolio Valuation : 982.94   |
Market Return : 26.58%   |   Portfolio Return : 54.78%   |   Portfolio Valuation : 1547.78   |
Market Return : 39.77%   |   Portfolio Return : 81.63%   |   Portfolio Valuation : 1816.29   |
Market Return : 43.37%   |   Portfolio Return : 97.04%   |   Portfolio Valuation : 1970.38   |
Market Return :  9.40%   |   Portfolio Return : 12.51%   |   Portfolio Valuation : 1125.13   |
Market Return : 685.28%   |   Portfolio Return : -713.74%   |   Portfolio Valuation : -6137.38   |
Market Return : 65.92%   |   Portfolio Return : -102.97%   |   Portfolio Valuation : -29.67   |
Market Return : 103.53%   |   Portfolio Return : 236.66%   |   Portfolio Valuation : 3366.62   |
Market Return : 26.58%   |   Portfolio Return : 52.64%   |   Portfolio Valuation : 1526.36   |
Market Return : 275.57%   |   Portfolio Return : -108.07%   |   Portfolio Valuation : -80.66   |
Market Return : 39.77%   |   Portfolio Return : 69.66%   |   Portfolio Valuation : 1696.59   |
Market Return : 43.37%   |   Portfolio Return : 96.36%   |   Portfolio Valuation : 1963.58   |
Market Return :  5.93%   |   Portfolio Return :  3.44%   |   Portfolio Valuation : 1034.41   |
Market Return :  9.40%   |   Portfolio Return : 14.81%   |   Portfolio Valuation : 1148.1   |
Market Return : 39.77%   |   Portfolio Return : 79.54%   |   Portfolio Valuation : 1795.44   |
Market Return : 26.58%   |   Portfolio Return : 55.02%   |   Portfolio Valuation : 1550.23   |
Market Return : 69.60%   |   Portfolio Return : -111.23%   |   Portfolio Valuation : -112.35   |
Market Return : 43.37%   |   Portfolio Return : 95.76%   |   Portfolio Valuation : 1957.64   |
Market Return : 103.53%   |   Portfolio Return : 265.44%   |   Portfolio Valuation : 3654.45   |
Market Return : 392.20%   |   Portfolio Return : -118.80%   |   Portfolio Valuation : -187.99   |
Market Return : 394.28%   |   Portfolio Return : -102.89%   |   Portfolio Valuation : -28.9   |
Market Return :  5.93%   |   Portfolio Return :  9.47%   |   Portfolio Valuation : 1094.69   |
Market Return : 26.58%   |   Portfolio Return : 55.33%   |   Portfolio Valuation : 1553.35   |
Market Return : 39.77%   |   Portfolio Return : 77.23%   |   Portfolio Valuation : 1772.29   |
Market Return : 699.62%   |   Portfolio Return : 155.09%   |   Portfolio Valuation : 2550.95   |
Market Return :  5.93%   |   Portfolio Return : -1.90%   |   Portfolio Valuation : 981.01   |
Market Return : 103.53%   |   Portfolio Return : 260.28%   |   Portfolio Valuation : 3602.81   |
Market Return : 579.70%   |   Portfolio Return : -311.26%   |   Portfolio Valuation : -2112.64   |
Market Return : 306.85%   |   Portfolio Return : -119.53%   |   Portfolio Valuation : -195.29   |
Market Return :  9.40%   |   Portfolio Return : 18.60%   |   Portfolio Valuation : 1186.0   |
Market Return : 43.37%   |   Portfolio Return : 94.78%   |   Portfolio Valuation : 1947.84   |
Market Return :  9.40%   |   Portfolio Return : 11.38%   |   Portfolio Valuation : 1113.8   |
Market Return :  5.93%   |   Portfolio Return : -1.66%   |   Portfolio Valuation : 983.36   |
Market Return : 946.44%   |   Portfolio Return : -72.79%   |   Portfolio Valuation : 272.15   |
Market Return : 76.78%   |   Portfolio Return : -100.06%   |   Portfolio Valuation : -0.65   |
Market Return : 43.37%   |   Portfolio Return : 94.13%   |   Portfolio Valuation : 1941.35   |
Market Return : 39.77%   |   Portfolio Return : 84.11%   |   Portfolio Valuation : 1841.08   |
Market Return : 103.53%   |   Portfolio Return : 260.79%   |   Portfolio Valuation : 3607.92   |
Market Return : 504.01%   |   Portfolio Return : -125.78%   |   Portfolio Valuation : -257.83   |
Market Return : 26.58%   |   Portfolio Return : 52.94%   |   Portfolio Valuation : 1529.38   |
Market Return : 369.71%   |   Portfolio Return : -180.70%   |   Portfolio Valuation : -806.97   |
Market Return :  5.93%   |   Portfolio Return : -6.05%   |   Portfolio Valuation : 939.5   |
Market Return : 69.60%   |   Portfolio Return : -103.13%   |   Portfolio Valuation : -31.28   |
Market Return :  9.40%   |   Portfolio Return : 18.69%   |   Portfolio Valuation : 1186.9   |
Market Return : 103.53%   |   Portfolio Return : 261.89%   |   Portfolio Valuation : 3618.95   |
Market Return : 114.68%   |   Portfolio Return : -104.47%   |   Portfolio Valuation : -44.7   |
Market Return : 39.77%   |   Portfolio Return : 77.15%   |   Portfolio Valuation : 1771.54   |
Market Return : 43.37%   |   Portfolio Return : 100.66%   |   Portfolio Valuation : 2006.6   |
Market Return : 26.58%   |   Portfolio Return : -57.77%   |   Portfolio Valuation : 422.3   |
Market Return :  5.93%   |   Portfolio Return : -60.74%   |   Portfolio Valuation : 392.56   |
Market Return : 26.58%   |   Portfolio Return : 42.10%   |   Portfolio Valuation : 1420.99   |
Market Return : 103.53%   |   Portfolio Return : 263.31%   |   Portfolio Valuation : 3633.13   |
Market Return : 685.28%   |   Portfolio Return : -893.09%   |   Portfolio Valuation : -7930.88   |
Market Return :  9.40%   |   Portfolio Return : 17.40%   |   Portfolio Valuation : 1174.03   |
Market Return : 699.62%   |   Portfolio Return : -99.34%   |   Portfolio Valuation : 6.56   |
Market Return : 43.37%   |   Portfolio Return : 60.17%   |   Portfolio Valuation : 1601.69   |
Market Return : 369.71%   |   Portfolio Return : -228.07%   |   Portfolio Valuation : -1280.66   |
Market Return : 39.77%   |   Portfolio Return : 78.19%   |   Portfolio Valuation : 1781.89   |
Market Return : 672.24%   |   Portfolio Return : -110.26%   |   Portfolio Valuation : -102.64   |
Market Return : 39.77%   |   Portfolio Return : 77.01%   |   Portfolio Valuation : 1770.14   |
Market Return : 26.58%   |   Portfolio Return : 48.50%   |   Portfolio Valuation : 1485.05   |
Market Return : 177.46%   |   Portfolio Return : -101.04%   |   Portfolio Valuation : -10.36   |
Market Return :  5.93%   |   Portfolio Return : -86.00%   |   Portfolio Valuation : 139.96   |
Market Return : 392.20%   |   Portfolio Return : -252.63%   |   Portfolio Valuation : -1526.26   |
Market Return : 43.37%   |   Portfolio Return : 67.58%   |   Portfolio Valuation : 1675.79   |
Market Return : 103.53%   |   Portfolio Return : 114.85%   |   Portfolio Valuation : 2148.5   |
Market Return :  9.40%   |   Portfolio Return : 18.64%   |   Portfolio Valuation : 1186.43   |
Market Return : 685.28%   |   Portfolio Return : -3550.61%   |   Portfolio Valuation : -34506.08   |
Market Return : 26.58%   |   Portfolio Return : 53.00%   |   Portfolio Valuation : 1529.98   |
Market Return : 369.71%   |   Portfolio Return : -308.21%   |   Portfolio Valuation : -2082.14   |
Market Return : 103.53%   |   Portfolio Return : 91.34%   |   Portfolio Valuation : 1913.38   |
Market Return : 148.20%   |   Portfolio Return : -134.69%   |   Portfolio Valuation : -346.87   |
Market Return :  5.93%   |   Portfolio Return : -46.67%   |   Portfolio Valuation : 533.27   |
Market Return :  9.40%   |   Portfolio Return : 14.90%   |   Portfolio Valuation : 1148.97   |
Market Return : 43.37%   |   Portfolio Return : 94.70%   |   Portfolio Valuation : 1947.01   |
Market Return : 39.77%   |   Portfolio Return : 88.36%   |   Portfolio Valuation : 1883.55   |
Market Return : 672.24%   |   Portfolio Return : -166.55%   |   Portfolio Valuation : -665.46   |
Market Return :  5.93%   |   Portfolio Return : -24.87%   |   Portfolio Valuation : 751.34   |
Market Return : 103.53%   |   Portfolio Return : -71.56%   |   Portfolio Valuation : 284.41   |
Market Return : 39.77%   |   Portfolio Return : -24.99%   |   Portfolio Valuation : 750.06   |
Market Return :  9.40%   |   Portfolio Return : -10.19%   |   Portfolio Valuation : 898.15   |
Market Return : 68.04%   |   Portfolio Return : -100.78%   |   Portfolio Valuation : -7.8   |
Market Return : 26.58%   |   Portfolio Return : 17.65%   |   Portfolio Valuation : 1176.51   |
Market Return : 43.37%   |   Portfolio Return : 39.31%   |   Portfolio Valuation : 1393.13   |
Market Return : 334.51%   |   Portfolio Return : -100.27%   |   Portfolio Valuation : -2.73   |
Market Return : 685.28%   |   Portfolio Return : -729.36%   |   Portfolio Valuation : -6293.58   |
Market Return : 39.77%   |   Portfolio Return : 59.67%   |   Portfolio Valuation : 1596.69   |
Market Return : 103.53%   |   Portfolio Return : 263.44%   |   Portfolio Valuation : 3634.41   |
Market Return :  5.93%   |   Portfolio Return :  9.60%   |   Portfolio Valuation : 1095.96   |
Market Return : 347.65%   |   Portfolio Return : -281.00%   |   Portfolio Valuation : -1810.04   |
Market Return : 43.37%   |   Portfolio Return : 69.44%   |   Portfolio Valuation : 1694.37   |
Market Return : 177.20%   |   Portfolio Return : -135.39%   |   Portfolio Valuation : -353.86   |
Market Return :  9.40%   |   Portfolio Return : 13.66%   |   Portfolio Valuation : 1136.62   |
Market Return : 26.58%   |   Portfolio Return : 44.79%   |   Portfolio Valuation : 1447.86   |
Market Return : 369.71%   |   Portfolio Return : -282.86%   |   Portfolio Valuation : -1828.59   |
Market Return : 26.58%   |   Portfolio Return : 45.95%   |   Portfolio Valuation : 1459.53   |
Market Return : 43.37%   |   Portfolio Return : 46.46%   |   Portfolio Valuation : 1464.61   |
Market Return :  5.93%   |   Portfolio Return :  1.30%   |   Portfolio Valuation : 1012.97   |
Market Return : 39.77%   |   Portfolio Return : 86.35%   |   Portfolio Valuation : 1863.51   |
Market Return :  9.40%   |   Portfolio Return : 18.66%   |   Portfolio Valuation : 1186.57   |
Market Return : 103.53%   |   Portfolio Return : 278.26%   |   Portfolio Valuation : 3782.59   |
Market Return : 186.86%   |   Portfolio Return : -112.91%   |   Portfolio Valuation : -129.07   |
Market Return : 685.28%   |   Portfolio Return : -2904.01%   |   Portfolio Valuation : -28040.11   |
Market Return : 99.02%   |   Portfolio Return : -117.96%   |   Portfolio Valuation : -179.56   |
Market Return : 39.77%   |   Portfolio Return : 52.32%   |   Portfolio Valuation : 1523.24   |
Market Return :  5.93%   |   Portfolio Return : -64.85%   |   Portfolio Valuation : 351.55   |
Market Return : 43.37%   |   Portfolio Return : 81.52%   |   Portfolio Valuation : 1815.2   |
Market Return : 26.58%   |   Portfolio Return : 52.81%   |   Portfolio Valuation : 1528.13   |
Market Return : 103.53%   |   Portfolio Return : 277.83%   |   Portfolio Valuation : 3778.3   |

In [13]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -12.12%   |   Portfolio Valuation : 878.83   |
Épisode terminé
Episode n˚2 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -653.78%   |   Portfolio Valuation : -5537.75   |
Argent perdu
Episode n˚3 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -24.12%   |   Portfolio Valuation : 758.77   |
Épisode terminé
Episode n˚4 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 46.06%   |   Portfolio Valuation : 1460.65   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 65.91%   |   Portfolio Valuation : 1659.11   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return : 10.22%   |   Portfolio Valuation : 1102.24   |
Épisode terminé
Episode n˚7 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 175.57%   |   Portfolio Return : -103.03%   |   Portfolio Valuation : -30.29   |
Argent perdu
Episode n˚8 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 369.71%   |   Portfolio Return : -253.22%   |   Portfolio Valuation : -1532.19   |
Argent perdu
Episode n˚9 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -608.39%   |   Portfolio Valuation : -5083.89   |
Argent perdu
Episode n˚10 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -7.23%   |   Portfolio Valuation : 927.75   |
Épisode terminé
Episode n˚11 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 61.02%   |   Portfolio Valuation : 1610.22   |
Épisode terminé
Episode n˚12 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 422.77%   |   Portfolio Return : -103.76%   |   Portfolio Valuation : -37.63   |
Argent perdu
Episode n˚13 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 57.60%   |   Portfolio Valuation : 1575.95   |
Épisode terminé
Episode n˚14 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -28.18%   |   Portfolio Valuation : 718.25   |
Épisode terminé
Episode n˚15 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -938.52%   |   Portfolio Valuation : -8385.23   |
Argent perdu
Episode n˚16 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return :  3.78%   |   Portfolio Valuation : 1037.76   |
Épisode terminé
Episode n˚17 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 186.86%   |   Portfolio Return : -108.28%   |   Portfolio Valuation : -82.79   |
Argent perdu
Episode n˚18 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 51.03%   |   Portfolio Valuation : 1510.26   |
Épisode terminé
Episode n˚19 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -28.21%   |   Portfolio Valuation : 717.87   |
Épisode terminé
Episode n˚20 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 118.92%   |   Portfolio Valuation : 2189.16   |
Épisode terminé
Episode n˚21 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return :  9.40%   |   Portfolio Return : -20.74%   |   Portfolio Valuation : 792.6   |
Épisode terminé
Episode n˚22 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.77%   |   Portfolio Return : 57.45%   |   Portfolio Valuation : 1574.46   |
Épisode terminé
Episode n˚23 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.93%   |   Portfolio Return : -30.40%   |   Portfolio Valuation : 695.95   |
Épisode terminé
Episode n˚24 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 43.37%   |   Portfolio Return : 81.81%   |   Portfolio Valuation : 1818.14   |
Épisode terminé
Episode n˚25 -- Jeu de donnée binance-ETHUSD-1h.pkl
Market Return : 347.65%   |   Portfolio Return : -215.16%   |   Portfolio Valuation : -1151.56   |
Argent perdu
Episode n˚26 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.53%   |   Portfolio Return : 96.84%   |   Portfolio Valuation : 1968.44   |
Épisode terminé
Episode n˚27 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 26.58%   |   Portfolio Return :  1.96%   |   Portfolio Valuation : 1019.64   |
Épisode terminé
Episode n˚28 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 685.28%   |   Portfolio Return : -252.72%   |   Portfolio Valuation : -1527.25   |
Argent perdu
Episode n˚29 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 161.14%   |   Portfolio Return : -153.28%   |   Portfolio Valuation : -532.79   |
Argent perdu
Episode n˚30 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 161.14%   |   Portfolio Return : -156.01%   |   Portfolio Valuation : -560.09   |
Argent perdu

In [ ]:
def preprocess_corrected(df):
    df = df.copy()
    
    df['feature_log_ret'] = np.log(df['close'] / df['close'].shift(1))

    df['feature_rsi'] = ta.rsi(df['close'], length=14) / 100.0 
    
    macd = ta.macd(df['close'])
    df['feature_macd_norm'] = macd['MACD_12_26_9'] / df['close']
    
    df['feature_atr_norm'] = ta.atr(df['high'], df['low'], df['close'], length=14) / df['close']
    
    df['feature_hour_sin'] = np.sin(2 * np.pi * df.index.hour / 24)
    df['feature_hour_cos'] = np.cos(2 * np.pi * df.index.hour / 24)

    df = df.dropna()
    
    df = df.replace([np.inf, -np.inf], 0)

    return df


def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 10*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1]))

def reward_function_rapport_market_v2(history):
    weight = 0 
    if (history['position',1] == history['position',-2]):
        weight = 0.1
    return 10*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - weight 

def reward_log_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = np.log(curr_val / prev_val)
    return reward

def reward_returns(history):
    # Rendement actuel du portefeuille
    prev_val = history['portfolio_valuation', -2]
    curr_val = history['portfolio_valuation', -1]
    
    # Protection division par zéro
    if prev_val == 0: return 0
    
    reward = (curr_val - prev_val) / prev_val
    return reward

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_corrected,
    reward_function=reward_returns,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[0, 1])
obs, _ = env.reset()

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=1_500_000)

In [ ]:
nb_episodes = 30

for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')