Nous allons, dans ce fichier, mettre en place l'algo de PPO pour notre agent RL.

In [1]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.3.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.23.2 (from pandas)
  Using cached numpy-2.3.5-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp311-cp311-win_amd64.whl (11.3 MB)
Using cached numpy-2.3.5-cp311-cp311-win_amd64.whl (13.1 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pandas/

In [3]:
!pip install gymnasium

Collecting gymnasium
  Using cached gymnasium-1.2.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.21.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (2.3.5)
Collecting cloudpickle>=1.2.0 (from gymnasium)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium) (4.15.0)
Collecting farama-notifications>=0.0.1 (from gymnasium)
  Using cached Farama_Notifications-0.0.4-py3-none-any.whl.metadata (558 bytes)
Using cached gymnasium-1.2.2-py3-none-any.whl (952 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached Farama_Notifications-0.0.4-py3-none-any.whl (2.5 kB)
Installing collected packages: farama-notifications, cloudpickle, gymnasium

   ------------- -------------------------- 1/3 [cloudpickle]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   -------------------------- ------------- 2/3 [gymnasium]
   ---------------------------------------- 3/3 [gymnasium]

Successfully installed cloudpickle-3.1.2 farama-notifications-0.0.4 gymnasium-1.2.2

In [37]:
!pip install gym_trading_env

Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
Exception ignored in: <_io.FileIO name=4 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=4>
Exception ignored in: <_io.FileIO name=5 mode='rb' closefd=True>
Traceback (most recent call last):
  File "c:\Users\mathi\OneDrive\Bureau\Cours 5a\RL\Projet\reinforcement-learning-project\.venv\Lib\site-packages\IPython\utils\_process_win32.py", line 138, in system
    res = process_handler(cmd, _system_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name=5>

Requirement already satisfied: gym_trading_env in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (0.3.5)
Requirement already satisfied: pandas>=1.5.3 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.3.3)
Requirement already satisfied: numpy>=1.21.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.3.5)
Requirement already satisfied: gymnasium>=0.28.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (1.2.2)
Requirement already satisfied: flask==2.2.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.2.5)
Requirement already satisfied: pyecharts>=2.0.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (2.0.9)
Requirement already satisfied: ccxt==3.0.59 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (3.0.59)
Requirement already satisfied: nest_asyncio in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gym_trading_env) (1.6.0)
Requirement already satisfied: setuptools>=60.9.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (65.5.0)
Requirement already satisfied: certifi>=2018.1.18 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (2025.11.12)
Requirement already satisfied: requests>=2.18.4 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (2.32.5)
Requirement already satisfied: cryptography>=2.6.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (46.0.3)
Requirement already satisfied: aiohttp>=3.8 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (3.13.2)
Requirement already satisfied: aiodns>=1.1.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (3.5.0)
Requirement already satisfied: yarl>=1.7.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from ccxt==3.0.59->gym_trading_env) (1.22.0)
Requirement already satisfied: Werkzeug>=2.2.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (3.1.4)
Requirement already satisfied: Jinja2>=3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (3.1.6)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (2.2.0)
Requirement already satisfied: click>=8.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from flask==2.2.5->gym_trading_env) (8.3.1)
Requirement already satisfied: pycares>=4.9.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiodns>=1.1.1->ccxt==3.0.59->gym_trading_env) (4.11.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (0.4.1)
Requirement already satisfied: idna>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from yarl>=1.7.2->ccxt==3.0.59->gym_trading_env) (3.11)
Requirement already satisfied: typing-extensions>=4.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from aiosignal>=1.4.0->aiohttp>=3.8->ccxt==3.0.59->gym_trading_env) (4.15.0)
Requirement already satisfied: colorama in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from click>=8.0->flask==2.2.5->gym_trading_env) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from cryptography>=2.6.1->ccxt==3.0.59->gym_trading_env) (2.0.0)
Requirement already satisfied: pycparser in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from cffi>=2.0.0->cryptography>=2.6.1->ccxt==3.0.59->gym_trading_env) (2.23)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium>=0.28.1->gym_trading_env) (3.1.2)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from gymnasium>=0.28.1->gym_trading_env) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from Jinja2>=3.0->flask==2.2.5->gym_trading_env) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym_trading_env) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym_trading_env) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pandas>=1.5.3->gym_trading_env) (2025.2)
Requirement already satisfied: prettytable in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pyecharts>=2.0.2->gym_trading_env) (3.17.0)
Requirement already satisfied: simplejson in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from pyecharts>=2.0.2->gym_trading_env) (3.20.2)
Requirement already satisfied: six>=1.5 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->gym_trading_env) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests>=2.18.4->ccxt==3.0.59->gym_trading_env) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from requests>=2.18.4->ccxt==3.0.59->gym_trading_env) (2.5.0)
Requirement already satisfied: wcwidth in c:\users\mathi\onedrive\bureau\cours 5a\rl\projet\reinforcement-learning-project\.venv\lib\site-packages (from prettytable->pyecharts>=2.0.2->gym_trading_env) (0.2.14)

In [2]:
import numpy as np
import pandas as pd
import gymnasium as gym
import gym_trading_env

In [4]:
def preprocess(df):
    df = df.sort_index()
    df = df.dropna()
    df = df.drop_duplicates()

    df['feature_close'] = (df['close'] - df['close'].mean()) / df['close'].std()

    return df

df = preprocess(pd.read_pickle('./data/yfinance-AAPL-1h.pkl'))
df.head(20)

,open,high,low,close,volume,date_close,feature_close
date_open,,,,,,,
2023-11-21 14:30:00,191.410004,191.520004,190.270004,190.347504,8992766,2023-11-21 15:30:00,-0.953609
2023-11-21 15:30:00,190.350006,190.470001,189.740005,189.942001,5681421,2023-11-21 16:30:00,-0.969213
2023-11-21 16:30:00,189.940002,190.320007,189.830002,190.274994,3359800,2023-11-21 17:30:00,-0.956399
2023-11-21 17:30:00,190.276993,190.600006,190.039993,190.119995,3112369,2023-11-21 18:30:00,-0.962363
2023-11-21 18:30:00,190.119995,190.615005,190.085007,190.380005,2874142,2023-11-21 19:30:00,-0.952358
2023-11-21 19:30:00,190.382797,190.710007,190.289993,190.649994,3442863,2023-11-21 20:30:00,-0.941969
2023-11-21 20:30:00,190.645004,190.729996,190.289993,190.660004,5535871,2023-11-21 21:30:00,-0.941583
2023-11-22 14:30:00,192.360001,192.929993,191.429993,191.931503,11546645,2023-11-22 15:30:00,-0.892655
2023-11-22 15:30:00,191.949997,192.369995,191.389999,191.660004,4786188,2023-11-22 16:30:00,-0.903103
2023-11-22 16:30:00,191.660004,191.960007,191.479996,191.914993,3340080,2023-11-22 17:30:00,-0.893291
2023-11-22 17:30:00,191.914993,192.089996,191.639999,192.005005,3467320,2023-11-22 18:30:00,-0.889827
2023-11-22 18:30:00,192.009995,192.030304,191.490005,191.634995,3409564,2023-11-22 19:30:00,-0.904065
2023-11-22 19:30:00,191.639999,191.639999,190.824997,191.512497,3992146,2023-11-22 20:30:00,-0.908779
2023-11-22 20:30:00,191.520004,191.699997,191.220001,191.300003,3537662,2023-11-22 21:30:00,-0.916956
2023-11-24 14:30:00,190.869995,190.899994,189.300003,189.460007,7873135,2023-11-24 15:30:00,-0.987760
2023-11-24 15:30:00,189.470001,189.669998,189.250000,189.610001,4853829,2023-11-24 16:30:00,-0.981988
2023-11-24 16:30:00,189.600006,189.788895,189.350006,189.539993,3827135,2023-11-24 17:30:00,-0.984682
2023-11-27 14:30:00,190.250702,190.299896,188.899994,189.059998,8344466,2023-11-27 15:30:00,-1.003153
2023-11-27 15:30:00,189.070007,189.500000,189.009995,189.494995,3959357,2023-11-27 16:30:00,-0.986414
2023-11-27 16:30:00,189.490005,190.509995,189.440002,190.369995,4866435,2023-11-27 17:30:00,-0.952743

In [ ]:
env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

In [13]:
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.env_checker import check_env

#print(check_env(env=env))

#vec_env = make_vec_env(env, n_envs=4)

model = PPO("MlpPolicy",env)

model.learn(total_timesteps=250000)
model.save("PPO_test1")

Market Return : 677.81%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return :  5.27%   |   Portfolio Return : -95.75%   |   Portfolio Valuation : 42.47   |
Market Return : 103.26%   |   Portfolio Return : -80.38%   |   Portfolio Valuation : 196.22   |
Market Return : 10.54%   |   Portfolio Return : -23.62%   |   Portfolio Valuation : 763.82   |
Market Return : 27.70%   |   Portfolio Return : -30.06%   |   Portfolio Valuation : 699.35   |
Market Return : 590.66%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : -0.02   |
Market Return : 39.94%   |   Portfolio Return : -14.62%   |   Portfolio Valuation : 853.82   |
Market Return : 279.25%   |   Portfolio Return : -100.03%   |   Portfolio Valuation : -0.3   |
Market Return : 44.45%   |   Portfolio Return : -27.32%   |   Portfolio Valuation : 726.77   |
Market Return : 39.94%   |   Portfolio Return : -47.66%   |   Portfolio Valuation : 523.36   |
Market Return : 27.70%   |   Portfolio Return :  3.41%   |   Portfolio Valuation : 1034.13   |
Market Return : 83.90%   |   Portfolio Return : -102.69%   |   Portfolio Valuation : -26.93   |
Market Return : 103.26%   |   Portfolio Return : -55.57%   |   Portfolio Valuation : 444.31   |
Market Return : 10.54%   |   Portfolio Return : -10.43%   |   Portfolio Valuation : 895.65   |
Market Return : 44.45%   |   Portfolio Return : -33.02%   |   Portfolio Valuation : 669.76   |
Market Return :  5.27%   |   Portfolio Return : -5.69%   |   Portfolio Valuation : 943.13   |
Market Return : 364.35%   |   Portfolio Return : -100.06%   |   Portfolio Valuation : -0.57   |
Market Return : 221.18%   |   Portfolio Return : -100.69%   |   Portfolio Valuation : -6.94   |
Market Return : 10.54%   |   Portfolio Return : -3.86%   |   Portfolio Valuation : 961.4   |
Market Return : 44.45%   |   Portfolio Return : -39.65%   |   Portfolio Valuation : 603.52   |
Market Return : 12.62%   |   Portfolio Return : -104.28%   |   Portfolio Valuation : -42.85   |

In [ ]:
i=0
obs,_ = env.reset()
while i<100:
    i+=1
    action, _states = model.predict(obs)
    print(action)
    obs, reward, terminated, truncated, info = env.step(action)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [14]:
nb_episodes = 3

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)


for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
    env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 95.06%   |   Portfolio Return : -101.35%   |   Portfolio Valuation : -13.46   |
Argent perdu
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.94%   |   Portfolio Return : -45.77%   |   Portfolio Valuation : 542.28   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.27%   |   Portfolio Return : -6.77%   |   Portfolio Valuation : 932.32   |
Épisode terminé

In [67]:
env.historical_info[-1]

{'idx': 2763,
 'step': 2763,
 'date': np.datetime64('2025-06-25T13:30:00.000000000'),
 'position_index': array(1),
 'position': 1,
 'real_position': np.float64(1.0000000000000002),
 'data_date_close': Timestamp('2025-06-25 14:30:00'),
 'data_close': 6100.830078125,
 'data_high': 6108.509765625,
 'data_volume': 0,
 'data_open': 6104.22998046875,
 'data_low': 6096.8798828125,
 'portfolio_valuation': np.float64(1346.3183462273655),
 'portfolio_distribution_asset': np.float64(0.22067789612018449),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': np.float64(1.1368683772161603e-13),
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': np.float64(9.473903143468003e-19),
 'reward': np.float64(0.0012383509773613998)}

Actuellement, les résultats sont trop aléatoirs, parfois l'agent apprend rapidement mais il n'est pas enclin à faire mieux que le marché. Il se contente de toujours garder son argent.
Nous allons améliorer notre programme de 2 manières:
    - Changer la fonction de reward, pour qu'elle récompense plus l'exploration
    - ajouter des features pour que l'agent comprenne mieux le marché

In [112]:
env.env.historical_info[-1]

{'idx': 42131,
 'step': 42131,
 'date': np.datetime64('2025-11-20T13:00:00.000000000'),
 'position_index': 13,
 'position': 1.4,
 'real_position': np.float64(1.398325122244509),
 'data_high': 0.13837,
 'data_low': 0.13651,
 'data_open': 0.13783,
 'data_date_close': Timestamp('2025-11-20 14:00:00'),
 'data_volume': 445127.0,
 'data_close': 0.13673,
 'portfolio_valuation': np.float64(1654.837230888517),
 'portfolio_distribution_asset': np.float64(16923.86801124077),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': np.float64(659.1577493071892),
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': np.float64(0.0054929812442265765),
 'reward': np.float64(-0.00355254135303337)}

In [104]:
def preprocess_v2(df):
    df = df.sort_index()
    df = df.dropna()
    df = df.drop_duplicates()

    # Valeur des différentes features par rapport à la moyenne
    df['feature_close'] = (df['close'] - df['close'].mean()) / df['close'].std()
    df['feature_high'] = (df['high'] - df['high'].mean()) / df['high'].std()
    df['feature_low'] = (df['low'] - df['low'].mean()) / df['low'].std()

    #Valeur des ratios entre 2 des 4 niveaux (haut/bas ou fermeture/ouverture)
    df['feature_ratio_high_low'] = (df['high'] / df['low'])
    df['feature_ratio_close_open'] = (df['close'] / df['open'])
    df['feature_ratio_high_close'] = (df['high'] / df['close'])

    #Valeur des features par rapport à leur max
    df['feature_max_ratio_close'] = (df['close'] - df['close'].max()) / df['close'].max()
    df['feature_max_ratio_open'] = (df['open'] - df['open'].max()) / df['open'].max()
    df['feature_max_ratio_low'] = (df['low'] - df['low'].max()) / df['low'].max()
    df['feature_max_ratio_high'] = (df['high'] - df['high'].max()) / df['high'].max()

    #Valeur des ratios par rapport à leur max entre 2 des 4 niveaux (haut/bas ou fermeture/ouverture)
    df['feature_ratio_max_high_low'] = (df['feature_ratio_high_low'] - df['feature_ratio_high_low'].max()) / df['feature_ratio_high_low'].max()
    df['feature_ratio_max__close_open'] = (df['feature_ratio_close_open'] - df['feature_ratio_close_open'].max()) / df['feature_ratio_close_open'].max()
    df['feature_ratio_max_high_close'] = (df['feature_ratio_high_close'] - df['feature_ratio_high_close'].max()) / df['feature_ratio_high_close'].max()

    return df

df = preprocess_v2(pd.read_pickle('./data/yfinance-AAPL-1h.pkl'))
df.head(5)

,open,high,low,close,volume,date_close,feature_close,feature_high,feature_low,feature_ratio_high_low,feature_ratio_close_open,feature_ratio_high_close,feature_max_ratio_close,feature_max_ratio_open,feature_max_ratio_low,feature_max_ratio_high,feature_ratio_max_high_low,feature_ratio_max__close_open,feature_ratio_max_high_close
date_open,,,,,,,,,,,,,,,,,,,
2023-11-21 14:30:00,191.410004,191.520004,190.270004,190.347504,8992766,2023-11-21 15:30:00,-0.953609,-0.934171,-0.930512,1.006570,0.994449,1.006160,-0.309597,-0.308964,-0.308235,-0.309390,-0.094637,-0.052735,-0.054685
2023-11-21 15:30:00,190.350006,190.470001,189.740005,189.942001,5681421,2023-11-21 16:30:00,-0.969213,-0.974486,-0.950975,1.003847,0.997857,1.002780,-0.311068,-0.312791,-0.310162,-0.313176,-0.097086,-0.049490,-0.057860
2023-11-21 16:30:00,189.940002,190.320007,189.830002,190.274994,3359800,2023-11-21 17:30:00,-0.956399,-0.980244,-0.947501,1.002581,1.001764,1.000237,-0.309860,-0.314271,-0.309835,-0.313717,-0.098224,-0.045768,-0.060250
2023-11-21 17:30:00,190.276993,190.600006,190.039993,190.119995,3112369,2023-11-21 18:30:00,-0.962363,-0.969494,-0.939393,1.002947,0.999175,1.002525,-0.310422,-0.313055,-0.309071,-0.312707,-0.097895,-0.048234,-0.058100
2023-11-21 18:30:00,190.119995,190.615005,190.085007,190.380005,2874142,2023-11-21 19:30:00,-0.952358,-0.968918,-0.937655,1.002788,1.001368,1.001234,-0.309479,-0.313621,-0.308907,-0.312653,-0.098038,-0.046145,-0.059312

In [ ]:
from gym_trading_env.wrapper import DiscreteActionsWrapper

def metric_portfolio_valuation(history):
    return round(history['portfolio_valuation', -1], 2)

def reward_function(history):
    return history['step']*(history['portfolio_valuation', -1] - history['portfolio_valuation', -2])

def reward_function_rapport_market(history):
    return 5*(history['data_open', -2] / history['data_close', -1])*((history['portfolio_valuation', -1] / history['portfolio_valuation', -2]) - (history['data_close', -1] / history['data_open', -1])) - (history['position',-1]/history['position',-2])

env = gym.make(
    "MultiDatasetTradingEnv",
    dataset_dir="data/*.pkl",
    preprocess=preprocess_v2,
    reward_function=reward_function_rapport_market,
    # Valeur initiale du portefeuille
    portfolio_initial_value=1_000,
    # Frais de transactions
    trading_fees=0.1/100,
    # Intérêts sur les prêts
    borrow_interest_rate=0.02/100/24,
)

env.add_metric('Portfolio Valuation', metric_portfolio_valuation)
env = DiscreteActionsWrapper(env, positions=[-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.5,0.6,0.8,1,1.2,1.4,1.6,1.8,2])
obs, _ = env.reset()

In [109]:
from stable_baselines3 import PPO

model = PPO("MlpPolicy",env)

model = model.learn(total_timesteps=300_000)

Market Return : 39.94%   |   Portfolio Return : -96.85%   |   Portfolio Valuation : 31.48   |
Market Return : 103.26%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.04   |
Market Return : 10.54%   |   Portfolio Return : -96.87%   |   Portfolio Valuation : 31.35   |
Market Return : 677.81%   |   Portfolio Return : -100.00%   |   Portfolio Valuation : 0.0   |
Market Return : 44.45%   |   Portfolio Return : -49.92%   |   Portfolio Valuation : 500.82   |
Market Return : 904.05%   |   Portfolio Return : -99.97%   |   Portfolio Valuation : 0.3   |
Market Return :  5.27%   |   Portfolio Return : -58.68%   |   Portfolio Valuation : 413.18   |
Market Return : 10.54%   |   Portfolio Return : -2.98%   |   Portfolio Valuation : 970.18   |
Market Return :  5.27%   |   Portfolio Return : -60.72%   |   Portfolio Valuation : 392.78   |
Market Return : 163.91%   |   Portfolio Return : -68.84%   |   Portfolio Valuation : 311.57   |
Market Return : 904.05%   |   Portfolio Return : 12.30%   |   Portfolio Valuation : 1123.02   |
Market Return : 103.26%   |   Portfolio Return : 58.95%   |   Portfolio Valuation : 1589.53   |
Market Return : 677.81%   |   Portfolio Return : -34.77%   |   Portfolio Valuation : 652.3   |
Market Return : 44.45%   |   Portfolio Return : 42.67%   |   Portfolio Valuation : 1426.66   |
Market Return : 27.70%   |   Portfolio Return : 27.42%   |   Portfolio Valuation : 1274.19   |
Market Return : 39.94%   |   Portfolio Return : 52.32%   |   Portfolio Valuation : 1523.21   |

In [110]:
nb_episodes = 10



for episode in range(1, nb_episodes + 1):
    obs, _ = env.reset()
    print(f'Episode n˚{episode} -- Jeu de donnée {env.env.name}')
    done = False

    while not done:
        action, _states = model.predict(obs)
        obs, reward, terminated, truncated, _ = env.step(action.tolist())
        done = terminated or truncated
    env.env.save_for_render(dir="logs")        
    if terminated:
        print('Argent perdu')
        
    elif truncated:
        print('Épisode terminé')

Episode n˚1 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 163.91%   |   Portfolio Return : 18.59%   |   Portfolio Valuation : 1185.9   |
Épisode terminé
Episode n˚2 -- Jeu de donnée yfinance-AAPL-1h.pkl
Market Return : 39.94%   |   Portfolio Return : 52.13%   |   Portfolio Valuation : 1521.26   |
Épisode terminé
Episode n˚3 -- Jeu de donnée yfinance-CAC40-1h.pkl
Market Return : 10.54%   |   Portfolio Return : 13.06%   |   Portfolio Valuation : 1130.59   |
Épisode terminé
Episode n˚4 -- Jeu de donnée binance-BTCUSD-1h.pkl
Market Return : 677.81%   |   Portfolio Return : 173.03%   |   Portfolio Valuation : 2730.35   |
Épisode terminé
Episode n˚5 -- Jeu de donnée yfinance-EURUSD-1h.pkl
Market Return :  5.27%   |   Portfolio Return : -28.68%   |   Portfolio Valuation : 713.15   |
Épisode terminé
Episode n˚6 -- Jeu de donnée yfinance-S&P500-1h.pkl
Market Return : 44.45%   |   Portfolio Return : 59.03%   |   Portfolio Valuation : 1590.3   |
Épisode terminé
Episode n˚7 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.26%   |   Portfolio Return : 71.76%   |   Portfolio Valuation : 1717.57   |
Épisode terminé
Episode n˚8 -- Jeu de donnée yfinance-STOXX50-1h.pkl
Market Return : 27.70%   |   Portfolio Return : 39.75%   |   Portfolio Valuation : 1397.51   |
Épisode terminé
Episode n˚9 -- Jeu de donnée yfinance-GOLDUSD-1h.pkl
Market Return : 103.26%   |   Portfolio Return : 70.33%   |   Portfolio Valuation : 1703.32   |
Épisode terminé
Episode n˚10 -- Jeu de donnée binance-DOGEEUR-1h.pkl
Market Return : 163.91%   |   Portfolio Return : 65.48%   |   Portfolio Valuation : 1654.84   |
Épisode terminé

In [81]:
env.env.historical_info[-1]

{'idx': 4509,
 'step': 4509,
 'date': np.datetime64('2025-11-21T13:00:00.000000000'),
 'position_index': 4,
 'position': 1,
 'real_position': np.float64(1.0),
 'data_high': 5531.83984375,
 'data_open': 5525.81982421875,
 'data_low': 5518.8798828125,
 'data_volume': 0,
 'data_delta_high_low': 1.002348295526029,
 'data_delta_open_close': 1.0009030758391957,
 'data_date_close': Timestamp('2025-11-21 14:00:00'),
 'data_close': 5530.81005859375,
 'portfolio_valuation': np.float64(1121.6929142246133),
 'portfolio_distribution_asset': np.float64(0.20280807012740049),
 'portfolio_distribution_fiat': 0,
 'portfolio_distribution_borrowed_asset': 0,
 'portfolio_distribution_borrowed_fiat': 0,
 'portfolio_distribution_interest_asset': 0.0,
 'portfolio_distribution_interest_fiat': 0.0,
 'reward': np.float64(-6.340988893560606e-05)}